FROM node:16-alpine

WORKDIR /app

COPY ./package.json ./package-lock.json  ./
COPY ./tsconfig.json ./tsconfig.build.json ./
COPY ./src ./src

RUN npm install

RUN apk --no-cache add tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone && \
        apk del tzdata

EXPOSE 3000

CMD npm run start:dev