export const BLOCK_ACTION = 'BLOCK_ACTION';
export const VIEW_SUBMISSION = 'VIEW_SUBMISSION';

export const DUTCH_PAY_CREATED_EVENT = 'DUTCH_PAY_CREATED_EVENT';
export const PARTICIPANT_PAID_BACK_EVENT = 'PARTICIPANT_PAY_BACK_EVENT';
